chore: add hpm6e00 series support
tfx2001/hpm_isp pull request #18
Opened 2024-09-27 08:03 UTC by Cherish-Gww

Add hpm6e00 support

2024-09-27 08:39 UTC, Cherish-Gww commented
@tfx2001 
Hi I have add hpm6e00 support

2024-09-27 15:13 UTC, tfx2001 commented on hpm_isp/src/hid.rs
> +	    Family::HPM6E00 => "HPM6E00",
请使用 4 space 缩进

2024-09-27 15:15 UTC, tfx2001 requested changes

2024-11-06 15:39 UTC, tfx2001 approved these changes

2024-11-06 15:40 UTC, merged